# -*- coding: utf-8 -*-
"""Projeto Tópicos de BigData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bs8FK4TDFs9-qXAdI9Dn5OJe2Lz7bN4p
"""

import pandas as pd
import numpy as ny
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Trabalho.csv", header=0)

df.head()

df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

df.info()

df.describe()

df.isnull().sum()

print(df.columns)

print(df.head(10))

print(df.tail(10))

df.replace("//", ny.nan, inplace=True)

df.head()

print(df.shape)

print(df.columns)

df.columns = [col.strip().replace('"', '') for col in df.columns]
df.columns = [col.strip() for col in df.columns]
df.columns

cura_leishmaniose = df['cura_leishmaniose']

print(cura_leishmaniose.unique())

print(cura_leishmaniose.nunique())

print(cura_leishmaniose.value_counts())

ano = df.sort_values(by='ano', ascending=True)

print(ano)

ano = df.sort_values(by='ano', ascending=False)

print(ano)

df.info()

df['raiva'] = pd.to_numeric(df['raiva'], errors='coerce')
df['leishmaniose'] = pd.to_numeric(df['leishmaniose'], errors='coerce')

plt.figure(figsize=(10,5))
plt.plot(df['ano'], df['raiva'], label='Casos de Raiva', marker='o')
plt.plot(df['ano'], df['leishmaniose'], label='Casos de Leishmaniose', marker='s')
plt.title("Casos de Raiva e Leishmaniose por Ano")
plt.xlabel("Ano")
plt.ylabel("Número de Casos")
plt.legend()
plt.grid(True)
plt.show()

df['óbitos_raiva'] = pd.to_numeric(df['óbitos_raiva'], errors='coerce')
df['óbitos_leishmaniose'] = pd.to_numeric(df['óbitos_leishmaniose'], errors='coerce')

plt.figure(figsize=(10,5))
plt.bar(df['ano'], df['óbitos_raiva'], width=0.4, label='Óbitos Raiva')
plt.bar(df['ano'] + 0.2, df['óbitos_leishmaniose'], width=0.4, label='Óbitos Leishmaniose')
plt.title("Óbitos por Ano")
plt.xlabel("Ano")
plt.ylabel("Número de Óbitos")
plt.legend()
plt.grid(True, axis='y')
plt.show()

plt.figure(figsize=(6,6))
plt.scatter(df['leishmaniose'], df['óbitos_leishmaniose'], color='red', label='Leishmaniose')
plt.scatter(df['raiva'], df['óbitos_raiva'], color='blue', label='Raiva')
plt.xlabel("Casos")
plt.ylabel("Óbitos")
plt.title("Relação entre Casos e Óbitos")
plt.legend()
plt.grid(True)
plt.show()

df['cura_leishmaniose'] = pd.to_numeric(df['cura_leishmaniose'], errors='coerce')
df['cura_raiva'] = pd.to_numeric(df['cura_raiva'], errors='coerce')

total_cura_leish = df['cura_leishmaniose'].sum()
total_cura_raiva = df['cura_raiva'].sum()

valores = [total_cura_leish, total_cura_raiva]
labels = ['Cura Leishmaniose', 'Cura Raiva']

plt.figure(figsize=(6,6))
plt.pie(valores, labels=labels, autopct='%1.1f%%', startangle=90)
plt.title("Proporção de Casos Curados")
plt.show()

df['cura_leishmaniose'] = pd.to_numeric(df['cura_leishmaniose'], errors='coerce')
df['cura_raiva'] = pd.to_numeric(df['cura_raiva'], errors='coerce')

plt.figure(figsize=(12,6))
plt.plot(df['ano'], df['raiva'], marker='o', label='Casos Raiva')
plt.plot(df['ano'], df['cura_raiva'], marker='s', label='Cura Raiva')
plt.plot(df['ano'], df['óbitos_raiva'], marker='^', label='Óbitos Raiva')

plt.plot(df['ano'], df['leishmaniose'], marker='o', linestyle='--', label='Casos Leishmaniose')
plt.plot(df['ano'], df['cura_leishmaniose'], marker='s', linestyle='--', label='Cura Leishmaniose')
plt.plot(df['ano'], df['óbitos_leishmaniose'], marker='^', linestyle='--', label='Óbitos Leishmaniose')

plt.title("Comparativo Geral — Casos, Curas e Óbitos")
plt.xlabel("Ano")
plt.ylabel("Quantidade")
plt.legend()
plt.grid(True)
plt.show()

df_filtro = df[df['raiva'] > 10]
df_filtro

df_filtro2 = df[(df['raiva'] > 10) & (df['leishmaniose'] > 5)]
df_filtro2

df_simpli = df[['ano', 'espécie', 'raiva', 'leishmaniose']]
df_simpli.head()

df_nulos = df[df['cura_leishmaniose'].isnull()]

df_valores = df[df['cura_leishmaniose'].notnull()]

print(df_nulos)

print(df_valores)

df.describe()

media_leishmaniose = df['leishmaniose'].mean()
mediana_leishmaniose = df['leishmaniose'].median()
desvio_leishmaniose = df['leishmaniose'].std()

print(f"Média: {media_leishmaniose:.2f}")
print(f"Mediana: {mediana_leishmaniose:.2f}")
print(f"Desvio padrão: {desvio_leishmaniose:.2f}")

df['casos_nao_curados_leishmaniose'] = df['leishmaniose'] - df['cura_leishmaniose']

df['situação_leishmaniose'] = ny.where(df['óbitos_leishmaniose'] > 0, 'Com óbitos', 'Sem óbitos')

df.head(100)

df_ordenado = df.sort_values(by='raiva', ascending=False)
df_ordenado.head()

max_raiva = df['raiva'].max()
max_leishmaniose = df['leishmaniose'].max()
ano_max_raiva = df.loc[df['raiva'] == max_raiva, 'ano'].values[0]
ano_max_leishmaniose = df.loc[df['leishmaniose'] == max_leishmaniose, 'ano'].values[0]

print(f"Maior número de casos de raiva: {max_raiva} (Ano: {ano_max_raiva})")
print(f"Maior número de casos de leishmaniose: {max_leishmaniose} (Ano: {ano_max_leishmaniose})")

resumo = {
    'Casos Totais Raiva': df['raiva'].sum(),
    'Casos Totais Leishmaniose': df['leishmaniose'].sum(),
    'Óbitos Totais Raiva': df['óbitos_raiva'].sum(),
    'Óbitos Totais Leishmaniose': df['óbitos_leishmaniose'].sum(),
    'Taxa média de cura Raiva (%)': (df['cura_raiva'].sum() / df['raiva'].sum()) * 100,
    'Taxa média de cura Leishmaniose (%)': (df['cura_leishmaniose'].sum() / df['leishmaniose'].sum()) * 100
}

for chave, valor in resumo.items():
    print(f"{chave}: {valor:.2f}")